name: Deploy Backend with Cloud Build

on:
  push:
    branches:
      - dev

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Submit build to Cloud Build
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          gcloud builds submit --config cloudbuild.yaml . \
            --gcs-source-staging-dir=gs://ardent-quarter-454807-h6_cloudbuild/source

      - name: Debug project and bucket
        run: |
          echo "Project: ${{ secrets.GCP_PROJECT_ID }}"
          gcloud config list
          gcloud builds submit --config cloudbuild.yaml . --verbosity=debug


